name: Run Screener Every Hour (Weekdays)

on:
  schedule:
    # Run every hour from 4:30 to 10:30 UTC → 9:30 AM to 3:30 PM IST, Monday to Friday
    - cron: '15 4-10 * * 1-5'
  workflow_dispatch:  # Optional manual trigger from GitHub UI

jobs:
  run-screener:
    runs-on: ubuntu-latest
    steps:
      - name: Call Screener Endpoint
        run: curl -X GET https://fastapi-trading-bot-1.onrender.com/run-screener
